### ISSUE TITLE
Displaying the Shoyu ramen pic

### ISSUE THREAD

**Issue by mmenakuru** [aponsero/Shiny_app_workshop_2020#1]
I cannot get the pic to display in the browser window that pops up.  I can see the header and the text but  not the pic or the footer.  I added it in to a new folder called www and it also exists in the same folder as the aPP.r

ui <- fluidPage( 
                # ----------------------------------
                h1("Best Ramens in the world", align = "center"),
                p("Explore the best ramens in the world, recommended by the users themselves! In this tab, you can 
                select your favorite ramen style and the country of fabrication. The table below display the best three 
                ramens for this selection!")
                HTML('<center><img src="1200px-Shoyu_Ramen.jpg" width="100%"></center>'),
                br()
                # ----------------------------------

) # end fluidpage panel

**Comment by aponsero** [comment]
Hi!
Thanks for your message! 
In the code you've pasted, I don't see the code calling for the image and the footer (it displays a broken link)... Do you have the footer call :   `includeHTML("footer.html")` ?


One thing that happened for others is that if the app script is not exactly called App.R it doesn't work.

Let me know if that helps

**Comment by mmenakuru** [comment]
Thank you for the response.  I was able to fix it.  Thanks again

**Comment by aponsero** [comment]
Glad to hear that! Good continuation!
